from enum import Enum, StrEnum, auto


class BoxTemplateName(StrEnum):
    BOX_ONE = "box1"
    BOX_TWO = "box2"
    BOX_THREE = "box3"
    BOX_FOUR = "box4"


class TemplateName(StrEnum):
    NEW_LEVEL = "newLevel"
    UNLOCK = "unlock"
    UPGRADE_STATION = "upgradeStation"
    RED_ICON = "RedIcon15"


class State(Enum):
    FIND_RED_ICONS = auto()
    CLICK_RED_ICON = auto()
    CHECK_UNLOCK = auto()
    SEARCH_UPGRADE_STATION = auto()
    HOLD_UPGRADE_STATION = auto()
    OPEN_BOXES = auto()
    UPGRADE_STATS = auto()
    SCROLL = auto()
    CHECK_NEW_LEVEL = auto()
    TRANSITION_LEVEL = auto()
    WAIT_FOR_UNLOCK = auto()


BOX_TEMPLATE_NAMES = tuple(template.value for template in BoxTemplateName)
RED_ICON_TEMPLATE_NAMES = (
    "RedIcon",
    *(f"RedIcon{index}" for index in range(2, 16)),
    "RedIconNoBG",
)
REQUIRED_TEMPLATE_NAMES = (
    TemplateName.NEW_LEVEL.value,
    TemplateName.UNLOCK.value,
    TemplateName.UPGRADE_STATION.value,
    *BOX_TEMPLATE_NAMES,
    *RED_ICON_TEMPLATE_NAMES,
)

MAX_UPGRADE_SEARCH_ATTEMPTS = 5
MAX_LEVEL_TRANSITION_ATTEMPTS = 3

SUCCESSFUL_RED_ICON_ROWS_LIMIT = 24
SEARCH_CYCLES_BEFORE_SCROLL = 2
FAILED_CLICK_BUCKET_LIMIT = 3
RED_ICON_FALLBACK_MIN_DISTANCE = 80
ICON_MERGE_DISTANCE_PIXELS = 10
ROW_PRIORITY_DISTANCE_PIXELS = 50
CLICK_BUCKET_SIZE_PIXELS = 30
SUCCESSFUL_ROW_DEDUP_DISTANCE_PIXELS = 12

UPGRADE_STATION_THRESHOLD_RELAXATION = 0.05
UPGRADE_STATION_HOLD_MIN_VERIFY_INTERVAL = 0.05
UPGRADE_STATION_HOLD_MAX_VERIFY_INTERVAL = 0.20
UPGRADE_STATS_CYCLE_INTERVAL = 2

BOT_STATE_LOOP_SLEEP_SECONDS = 0.10
CHECK_NEW_LEVEL_PRE_CLICK_DELAY = 0.05
TRANSITION_LEVEL_BUTTON_WAIT_SECONDS = 1.00
TRANSITION_LEVEL_RETRY_DELAY_SECONDS = 0.20
WAIT_FOR_UNLOCK_PRE_SCAN_DELAY = 0.05
WAIT_FOR_UNLOCK_RETRY_DELAY = 0.30
WAIT_FOR_UNLOCK_POST_CLICK_DELAY = 0.50
